import {
    ShoppingCart,
    Menu,
    ChevronLeft,
    ChevronRight,
    Loader2,
    Check,
    Plus,
    ChevronDown,
    ChevronsLeft,
    ChevronsRight,
    Image,
    Trash2,
    Search,
} from "lucide-react"

export const Icons = {
    shoppingCart: ShoppingCart,
    menu: Menu,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    spinner: Loader2,
    check: Check,
    add: Plus,
    chevronDown: ChevronDown,
    chevronsLeft: ChevronsLeft,
    chevronsRight: ChevronsRight,
    placeholder: Image,
    trash: Trash2,
    search: Search,
}